baseurl = "https://dsoloh.me"
title = "Dmytro S."
theme = "Coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 10

[services]
[services.disqus]
shortname = "dsoloh"

[markup.highlight]
style = "github-dark"

[params]
  author = "Dmytro Solohub"
  info = "Software Engineer & Team Lead"
  description = "Dmytro Solohub's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar-color.jpg"
  #gravatar = "sologub.da@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024
  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = true

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/sologubd/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://linkedin.com/in/dsoloh"
#[[params.social]]
#  name = "X"
#  icon = "fa-brands fa-x-twitter fa-2x"
#  weight = 3
#  url = "https://x.com/dsoloh/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
